### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by javathunderman** [Emposoft/CefSharp#1]
Had nowhere else to write this, lol. 

@AJDev77 Created this new repo. You should be able to clone, commit, delete, etc. Preferably, we'll get CEF sorted out so we can go back to handling some of the issues in the main MySurf repo, but until then, here you go. 

@amaitland You should see a PR soon.

**Comment by AJDev77** [comment]
@javathunderman @amaitland I am going to keep <code>CefSharp</code> as it is for now, because I want to get the browser up and running to get a stable release out.

**Comment by javathunderman** [comment]
Closing this as it seems pointless to keep this open.

**Comment by amaitland** [comment]
FYI Have released `39.0.0` to our `MyGet` feed, in the next few days after some final double checking it'll be uploaded to `Nuget.org`

Probably in a week or so I'll look at releasing a `41.0.0-pre01` version.

Happy to discuss any thoughts/requirements you have for a `41.0.0` release of `CefSharp.
